export const theme = {
  background: 'rgba(255, 213, 1, 0.08)',
  badge_background: 'red',
  badge_text: 'white',
  button_background: 'orange',
  button_text: 'white',
  navbar: 'hsl(50, 100%, 47%)',
  nav_height: '54px',
  nav_link_text: 'white',
  nav_link_selected_text: 'orange',
  nav_link_selected_background: 'white',
  sidebar_background: 'white',
  sidebar_width: '40vw',
  z_index_navbar: 1000,
}
